repos:
  - repo: local
    hooks:
      - id: htmlhint
        name: HTMLHint
        language: system
        entry: npm run lint:html --
        pass_filenames: false
        files: \.html$

      - id: eslint
        name: ESLint
        language: system
        entry: npm run lint:js --
        pass_filenames: false
        files: \.html$
